MusicStore/MusicStoreWeb/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicStoreWeb.Models.AlbumViewModels;
using MusicStoreWeb.Services.Contracts;
using System.Threading.Tasks;

namespace MusicStoreWeb.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        private readonly IAlbumService albumService;

        public AlbumsController(IAlbumService albumService)
        {
            this.albumService = albumService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> ListAll(int page = 1)
        {
            var albums = await this.albumService.ListAllAsync(page);

            return View(new AlbumListingViewModel
            {
                AllAlbums = albums,
                CurrentPage = page,
                TotalAlbums = await this.albumService.TotalAsync()
            });
        }

        public async Task<IActionResult> Details(int Id)
        {
            var album = await this.albumService.DetailsAsync(Id);

            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }
    }
}

MusicStore/MusicStoreWeb/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStoreWeb.Models.ArtistViewModels;
using MusicStoreWeb.Services.Contracts;
using System.Threading.Tasks;

namespace MusicStoreWeb.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly IArtistService artistService;

        public ArtistsController(IArtistService artistService)
        {
            this.artistService = artistService;
        }

        public async Task<IActionResult> ListAll(int page = 1)
        {
            var allArtist = await this.artistService.AllAsync(page);

            return View(new ArtistListingViewModel
            {
                AllArtists = allArtist,
                TotalArtists = await this.artistService.TotalAsync(),
                CurrentPage = page
            });
        }
    }
}

MusicStore/MusicStoreWeb/Controllers/SongsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicStoreWeb.Models.SongViewModels;
using MusicStoreWeb.Services.Contracts;
using System.Threading.Tasks;

namespace MusicStoreWeb.Controllers
{
    [Authorize]
    public class SongsController : Controller
    {
        private readonly ISongService songService;
        public SongsController(ISongService songService)
        {
            this.songService = songService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> ListAll(int page = 1)
        {
            var allSongs = await this.songService.AllAsync(page);

            return View(new SongListingViewModel
            {
                AllSongs = allSongs,
                CurrentPage = page,
                TotalSongs = await this.songService.TotalAsync()
            });
        }

        public async Task<IActionResult> Details(int id)
        {
            var song = await this.songService.DetailsAsync(id);

            if (song == null)
            {
                return BadRequest();
            }

            return View(song);
        }
    }
}

MusicStore/MusicStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicStoreWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicStoreWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(MusicStoreWeb.Infrastructure.Common.WebConstants.AdministratingRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Artists" asp-action="ListAll">Artists</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Songs" asp-action="ListAll">Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Albums" asp-action="ListAll">Albums</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Artists" asp-action="ListAll">Artists</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Songs" asp-action="ListAll">Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Albums" asp-action="ListAll">Albums</a>
                            </li>
                            <li class="nav-item">
                                @await Component.InvokeAsync("ShoppingCartSummary")
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MusicStoreWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>